version: "3.5"

services:
  cutter:
    build:
      dockerfile: Dockerfile
      context: cutter
    volumes:
      - ./images:/images
  distribution:
    build:
      dockerfile: Dockerfile
      context: distribution
    volumes:
      - ./images:/images
      - ./distributionImages:/distributionImages